version: "3.7"

services:
  app:
    env_file: .env
    build: .
    ports:
      - 4000:4000
    depends_on:
      - db
    links:
      - db
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
  db:
    env_file: .env
    image: postgres:16-alpine
    restart: always
    environment:
      # https://docs.docker.com/compose/environment-variables/set-environment-variables/#substitute-from-the-shell
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - postgres_db:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  postgres_db:
    driver: local
