version: "3.7"

services:

  app:
    # TODO: use env_file
    image: .
    ports:
      - 4000:4000
    depends_on:
      - db
    links:
      - db
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  db:
    image: postgres:16-alpine
    restart: always
    # TODO: use env_file
    environment:
      # https://docs.docker.com/compose/environment-variables/set-environment-variables/#substitute-from-the-shell
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - postgres_db:/var/lib/postgresql/data
    ports:
      - 5432:5432


volumes:
  postgres_db:
    driver: local
